---
log:
  level: debug
clients:
  - module: ./middleware/patmos-default-client
  - pattern:
      resource: 'auth'
    module: ./middleware/patmos-rest-client
    method:
      name: default
      args:
        - path: /v1/auth/:item
middleware:
  - module: ./middleware/patmos-timestamp
methods:
  - pattern:
      role: middleware
      cmd: timestamp
    module: ./lib/methods
    method: timestamp
scopes:
  - pattern:
      resource: users
    servers:
      - module: ./middleware/patmos-rest-server
        method:
          name: default
          args:
            - path: /v1/users/:item
    methods:
      - pattern:
          method: DEL
        module: ./lib/methods
        method: delUsers
      - pattern:
          method: GET
        module: ./lib/methods
        method: getUsers
      - pattern:
          method: PUT
        module: ./lib/methods
        method: putUsers
      - pattern:
          method: POST
        module: ./lib/methods
        method: postUsers
